;;;; packages.lisp — package definitions for AUTOMA GP

(defpackage #:automa-gp
  (:use #:cl)
  (:export
   ;; version
   #:*version*
   ;; modes
   #:*valid-modes*
   #:mode-p
   #:ensure-mode
   #:mode-allows-mutation-p
   ;; matcher / bindings
   #:*fail*
   #:*no-bindings*
   #:fail-p
   #:variable-symbol-p
   #:anonymous-variable-p
   #:lookup-binding
   #:extend-bindings
   #:substitute-bindings
   #:match
   #:match-p
   #:match-all
   ;; unification
   #:occurs-check-p
   #:unify
   #:unify-p
   ;; facts
   #:fact-equal
   #:fact-matches-p
   #:fact-p
   #:fact-same-names-p
   #:find-fact-by-names
   #:find-facts
   #:add-fact!
   #:remove-fact!
   #:facts-of
   ;; context
   #:context
   #:context-p
   #:context-name
   #:context-parent
   #:context-children
   #:context-facts
   #:context-goals
   #:context-actions
   #:context-rules
   #:context-operators
   #:context-events
   #:context-event-reactions
   #:context-mode
   #:context-meta
   #:make-context
   #:create-context
   #:context-add-child!
   #:context-query
   #:context-modify!
   #:clone-context
   #:compare-contexts
   #:context-all-facts
   #:context-all-rules
   #:context-all-operators
   #:context-planning-operators
   #:context-all-event-reactions
   ;; state
   #:state
   #:state-p
   #:state-facts
   #:state-source
   #:state-kind
   #:*valid-state-kinds*
   #:make-state
   #:state-from-context
   #:state-equal
   #:compare-states
   #:transition-facts
   #:transition-state
   ;; goals
   #:add-goal!
   #:remove-goal!
   #:goals-of
   #:goal-active-p
   ;; actions
   #:action
   #:action-p
   #:action-name
   #:action-parameters
   #:action-preconditions
   #:action-effects
   #:action-cost
   #:action-risk
   #:action-reversible
   #:action-adapter
   #:action-authorization
   #:make-action
   #:register-action!
   #:find-action
   #:actions-of
   #:action-applicable-p
   ;; rules
   #:rule
   #:rule-p
   #:rule-name
   #:rule-if
   #:rule-then
   #:rule-meta
   #:make-rule
   #:register-rule!
   #:remove-rule!
   #:rules-of
   #:rule-conclusions
   #:forward-chain
   #:*forward-chain-limit*
   ;; queries
   #:query
   #:query-facts
   #:query-bindings
   #:prove
   #:prove-all
   #:*query-depth-limit*
   ;; operators
   #:operator
   #:operator-p
   #:operator-name
   #:operator-parameters
   #:operator-preconditions
   #:operator-add-list
   #:operator-delete-list
   #:operator-cost
   #:operator-action
   #:operator-reversible
   #:operator-risk
   #:operator-meta
   #:make-operator
   #:*observed-before*
   #:*observation*
   #:*listen-on-plan-failure*
   #:observation-active-p
   #:gp-observation
   #:induce-operator
   #:gp-listen
   #:gp-note-state
   #:gp-learn-action
   #:gp-induce-rule
   #:action->operator
   #:register-operator!
   #:remove-operator!
   #:operators-of
   #:find-operator
   #:operator-achieves
   #:operators-for-goal
   ;; MEA
   #:*plan-depth-limit*
   #:goal-holds-p
   #:differences
   #:apply-operator
   #:precondition-subgoals
   #:achieve
   #:achieve-all
   #:means-ends-analyze
   ;; planner
   #:plan
   #:plan-p
   #:plan-goals
   #:plan-steps
   #:plan-success
   #:plan-initial-state
   #:plan-final-state
   #:plan-remaining
   #:plan-operators-used
   #:plan-meta
   #:plan-for
   #:plan-from-context
   #:plan-length
   #:plan-cost
   #:normalize-planning-goals
   #:*current-plan*
   ;; conditions / restarts (Phase 5)
   #:gp-condition
   #:gp-error
   #:gp-condition-operator
   #:gp-condition-bindings
   #:gp-condition-step
   #:gp-condition-mode
   #:gp-condition-context
   #:precondition-failure
   #:precondition-failure-missing
   #:precondition-failure-operator
   #:precondition-failure-bindings
   #:confirmation-required
   #:confirmation-required-reason
   #:confirmation-required-operator
   #:confirmation-required-bindings
   #:unknown-operator
   #:unknown-operator-name
   #:action-failed
   #:action-failed-reason
   #:deliberative-strategy
   #:make-strategy
   #:strategy-policy
   #:strategy-retry-limit
   #:strategy-retry-count
   #:strategy-events
   #:strategy-skipped
   #:*deliberative-strategy*
   #:*ask-user-fn*
   #:*plan-runner-default-abort*
   #:*gp-alternative-operator*
   #:record-strategy-event
   #:strategy-events-of
   #:with-failure-strategy
   #:maybe-invoke-strategy
   #:plan-runner-condition-handler
   #:call-with-gp-restarts
   #:make-step-result
   ;; executor / simulation
   #:execution-result
   #:execution-result-p
   #:execution-mode
   #:execution-success
   #:execution-steps
   #:execution-current-state
   #:execution-expected-state
   #:execution-final-state
   #:execution-divergences
   #:execution-plan
   #:execution-strategy-events
   #:execution-meta
   #:*last-execution*
   #:*execution-confirm*
   #:expected-state-from-plan
   #:operator-needs-confirmation-p
   #:simulate-operator
   #:simulate-plan
   #:execute-operator!
   #:execute-plan!
   ;; explanation / deliberative trace (Phase 6)
   #:*trace-enabled*
   #:*current-trace*
   #:*last-trace*
   #:*trace-history*
   #:*trace-history-limit*
   #:deliberative-trace
   #:deliberative-trace-p
   #:trace-id
   #:trace-phase
   #:trace-context-name
   #:trace-entries
   #:trace-open-p
   #:trace-started-at
   #:trace-finished-at
   #:make-trace
   #:trace-record
   #:finalize-trace
   #:with-trace
   #:last-trace
   #:trace-of
   #:find-trace-entries
   #:clear-trace-session
   #:resolve-explain-topic
   #:format-explanation
   #:explain-trace
   #:narrate-trace
   #:gp-narrate
   #:gp-explain
   #:gp-last-trace
   #:gp-trace-history
   ;; working memory (Phase 7)
   #:*working-memory*
   #:working-memory
   #:working-memory-p
   #:working-memory-context-name
   #:working-memory-facts
   #:working-memory-goals
   #:working-memory-mode
   #:working-memory-captured-at
   #:capture-working-memory
   #:refresh-working-memory
   #:clear-working-memory
   #:working-memory-state
   ;; knowledge memory (Phase 7)
   #:*knowledge-memory*
   #:knowledge-memory
   #:knowledge-memory-p
   #:knowledge-memory-name
   #:knowledge-memory-facts
   #:knowledge-memory-rules
   #:knowledge-memory-meta
   #:make-knowledge-memory
   #:ensure-knowledge-memory
   #:clear-knowledge-memory
   #:knowledge-add-fact!
   #:knowledge-remove-fact!
   #:knowledge-add-rule!
   #:knowledge-remove-rule!
   #:knowledge-query
   #:knowledge-from-context
   #:knowledge-merge-into-context!
   ;; episodic memory (Phase 7)
   #:*episodic-memory*
   #:*episodic-memory-limit*
   #:episode
   #:episode-p
   #:episode-id
   #:episode-kind
   #:episode-context-name
   #:episode-summary
   #:episode-success
   #:episode-payload
   #:episode-timestamp
   #:episodic-memory
   #:episodic-memory-p
   #:episodic-memory-episodes
   #:episodic-memory-limit
   #:make-episodic-memory
   #:ensure-episodic-memory
   #:clear-episodic-memory
   #:record-episode!
   #:record-plan-episode!
   #:record-execution-episode!
   #:find-episodes
   #:last-episode
   ;; procedural memory (Phase 7)
   #:*procedural-memory*
   #:gp-procedure
   #:procedure-p
   #:procedure-name
   #:procedure-goals
   #:procedure-steps
   #:procedure-operators-used
   #:procedure-initial-state
   #:procedure-success-count
   #:procedure-failure-count
   #:procedure-last-success-at
   #:procedure-last-failure-at
   #:procedure-score
   #:procedure-meta
   #:procedural-memory
   #:procedural-memory-p
   #:procedural-memory-procedures
   #:procedural-memory-meta
   #:make-procedural-memory
   #:ensure-procedural-memory
   #:clear-procedural-memory
   #:make-procedure
   #:procedure-from-plan
   #:remember-procedure!
   #:remember-procedure-from-plan!
   #:install-procedure!
   #:score-procedure!
   #:record-procedure-outcome!
   #:find-procedure
   #:procedures-for-goals
   #:rank-procedures
   #:archive-best
   #:procedure->plan
   #:replay-procedure
   #:plan-from-procedure
   #:plan-consulting-archive
   #:*procedure-repair-archive-depth*
   #:*procedure-archive-path*
   #:*procedure-archive-autosave*
   #:*procedure-archive-autoload*
   #:save-procedure-archive
   #:load-procedure-archive
   ;; persistence service (Phase 7)
   #:*persistence-format-version*
   #:*default-snapshot-directory*
   #:serialize-rule
   #:deserialize-rule
   #:serialize-operator
   #:deserialize-operator
   #:serialize-action
   #:deserialize-action
   #:serialize-context
   #:deserialize-context
   #:serialize-episode
   #:deserialize-episode
   #:serialize-procedure
   #:deserialize-procedure
   #:serialize-knowledge-memory
   #:deserialize-knowledge-memory
   #:serialize-episodic-memory
   #:deserialize-episodic-memory
   #:serialize-procedural-memory
   #:deserialize-procedural-memory
   #:suspend-context
   #:resume-context
   #:ensure-snapshot-path
   #:write-sexp-file
   #:read-sexp-file
   #:make-snapshot
   #:save-snapshot
   #:load-snapshot
   #:persist-context
   #:restore-context
   #:apply-snapshot!
   ;; session / REPL
   #:*current-context*
   #:gp-reset
   #:gp-context
   #:gp-state
   #:gp-facts
   #:gp-goals
   #:gp-actions
   #:gp-rules
   #:gp-operators
   #:gp-add-fact
   #:gp-remove-fact
   #:gp-add-goal
   #:gp-remove-goal
   #:gp-add-rule
   #:gp-remove-rule
   #:gp-add-operator
   #:gp-remove-operator
   #:gp-query
   #:gp-infer
   #:gp-plan
   #:gp-plan-open-goals
   #:gp-last-plan
   #:gp-simulate
   #:gp-run
   #:gp-last-execution
   #:gp-failure-strategy
   #:gp-mode
   #:gp-register-action
   #:gp-working
   #:gp-knowledge
   #:gp-knowledge-add
   #:gp-knowledge-query
   #:gp-knowledge-merge
   #:gp-episodes
   #:gp-last-episode
   #:gp-remember-procedure
   #:gp-procedures
   #:gp-find-procedure
   #:gp-archive
   #:gp-archive-best
   #:gp-archive-save
   #:gp-archive-load
   #:gp-use-procedure
   #:gp-score-procedure
   #:gp-save
   #:gp-load
   #:gp-save-context
   #:gp-load-context
   #:gp-clear-memory
   ;; OS adapters (Phase 8)
   #:*invoke-adapters*
   #:file-exists-p
   #:directory-files
   #:adapter-ensure-directory
   #:adapter-probe-file
   #:adapter-read-file-string
   #:adapter-write-file-string
   #:adapter-delete-file
   #:filesystem-dispatch
   #:run-program
   #:current-process-id
   #:process-running-p
   #:processes-dispatch
   #:macos-p
   #:adapter-hostname
   #:adapter-uname
   #:adapter-open
   #:macos-dispatch
   #:operator-external-spec
   #:plan-external-actions
   #:plan-external-actions-withheld
   #:plan-external-actions-supported-p
   #:plan-external-actions-match-p
   #:invoke-external-spec
   #:maybe-invoke-external!
   #:with-adapters-enabled
   #:gp-adapters
   ;; domain packs (Phase 9)
   #:*known-domains*
   #:gp-load-domain
   #:gp-domains
   ;; events (Phase 10)
   #:*event-counter*
   #:*last-reaction*
   #:gp-event
   #:event-p
   #:event-id
   #:event-type
   #:event-data
   #:event-timestamp
   #:event-status
   #:event-meta
   #:make-event
   #:event-form
   #:parse-event-form
   #:event-reaction
   #:event-reaction-p
   #:event-reaction-name
   #:event-reaction-when
   #:event-reaction-assert
   #:event-reaction-goals
   #:event-reaction-meta
   #:make-event-reaction
   #:register-event-reaction!
   #:remove-event-reaction!
   #:event-reactions-of
   #:match-event-reaction
   #:events-of
   #:pending-events
   #:clear-events!
   #:emit-event!
   #:react-to-event!
   #:process-pending-events!
   #:gp-notice-path
   #:gp-notice-directory
   #:gp-watch-directory
   #:gp-stop-directory-watch
   #:gp-directory-watch
   #:gp-notice-processes
   #:gp-watch-processes
   #:gp-stop-process-watch
   #:gp-process-watch
   #:gp-notice-terminals
   #:gp-watch-terminals
   #:gp-stop-terminal-watch
   #:gp-terminal-watch
   #:gp-notice-terminal-text
   #:gp-watch-terminal-text
   #:gp-stop-terminal-text-watch
   #:gp-terminal-text-watch
   #:gp-notice-terminal-screen
   #:gp-watch-terminal-screen
   #:gp-stop-terminal-screen-watch
   #:gp-terminal-screen-watch
   #:gp-interpret
   #:gp-ask
   #:gp-name-operator
   #:gp-emit
   #:gp-events
   #:gp-react
   #:gp-add-reaction
   #:gp-remove-reaction
   #:gp-reactions
   #:gp-last-reaction
   ;; web API façade (Phase 11; HTTP via automa-gp/web)
   #:*web-api-version*
   #:json-escape-string
   #:json-array
   #:lisp->json
   #:json->lisp
   #:json-string->symbol
   #:json->sexp
   #:web-api-handle
   #:web-api-handle-json
   ;; autonomy (Phase 12)
   #:*valid-authorities*
   #:*autonomy-policy*
   #:*last-autonomy*
   #:autonomy-policy
   #:autonomy-policy-p
   #:policy-authority
   #:policy-max-steps
   #:policy-adapters
   #:policy-auto-confirm
   #:policy-confirm-fn
   #:policy-react-events
   #:policy-infer
   #:policy-learn
   #:policy-replan-on-discrepancy
   #:policy-remember-procedure
   #:policy-prefer-archive
   #:ensure-authority
   #:make-autonomy-policy
   #:ensure-autonomy-policy
   #:authority>=
   #:plan-requires-confirmation-p
   #:plan-risky-operators
   #:goals-satisfied-p
   #:autonomy-open-goals
   #:autonomy-has-work-p
   #:autonomous-step
   #:autonomous-loop
   #:gp-policy
   #:gp-autonomous-step
   #:gp-autonomous-loop
   #:gp-last-autonomy
   ;; utilities
   #:not-yet-implemented
   #:not-yet-implemented-error))
