;;;; tests/test-archive.lisp — persistent scored procedure archive: scoring, files, reuse in planning

(in-package #:automa-gp/tests)

(def-suite archive-suite :in automa-gp-suite)
(in-suite archive-suite)

(defun %archive-studio ()
  "Fresh context and a successful connect plan. Keeps the procedure archive."
  (gp-reset)
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(power-state interface-01 off))
  (gp-add-operator
   (make-operator :name 'power-on
                  :preconditions '((device ?d) (power-state ?d off))
                  :add-list '((power-state ?d on))
                  :delete-list '((power-state ?d off))))
  (gp-add-operator
   (make-operator :name 'connect
                  :preconditions '((device ?d) (power-state ?d on))
                  :add-list '((connection ?d computer))))
  (gp-plan :goals '((connection interface-01 computer))))

(test archive-scores-repeat-success-above-a-failure
  (gp-clear-memory)
  (%archive-studio)
  (let ((once (gp-remember-procedure :name 'once)))
    (is (= 1 (procedure-success-count once)))
    (is (= 0 (procedure-failure-count once))))
  (%archive-studio)
  (let ((twice (gp-remember-procedure :name 'once)))
    (is (= 2 (procedure-success-count twice))))
  (gp-remember-procedure :name 'shaky)
  (gp-score-procedure 'shaky :success nil)
  (let ((best (gp-archive-best '((connection interface-01 computer)))))
    (is (eq 'once (procedure-name best)))
    (is (> (procedure-score (gp-find-procedure 'once))
           (procedure-score (gp-find-procedure 'shaky)))))
  (let ((ranked (gp-archive)))
    (is (eq 'once (procedure-name (first ranked))))))

(test archive-file-roundtrip-and-use-without-search
  (let* ((path (merge-pathnames
                (format nil "automa-gp-archive-~A.agp" (get-universal-time))
                (uiop:temporary-directory)))
         (*procedure-archive-path* path)
         (*procedure-archive-autosave* t)
         (*procedure-archive-autoload* nil))
    (unwind-protect
         (progn
           (gp-clear-memory)
           (%archive-studio)
           (gp-remember-procedure :name 'connect-iface)
           (is (probe-file path))
           (gp-clear-memory)
           (is (null (gp-find-procedure 'connect-iface)))
           (gp-archive-load path)
           (let ((found (gp-find-procedure 'connect-iface)))
             (is (procedure-p found))
             (is (= 1 (procedure-success-count found)))
             (is (plusp (procedure-score found))))
           (gp-reset)
           (signals error (gp-use-procedure :name 'connect-iface))
           (gp-add-fact '(device interface-01))
           (gp-add-fact '(power-state interface-01 off))
           (gp-add-operator
            (make-operator :name 'power-on
                           :preconditions '((device ?d) (power-state ?d off))
                           :add-list '((power-state ?d on))
                           :delete-list '((power-state ?d off))))
           (gp-add-operator
            (make-operator :name 'connect
                           :preconditions '((device ?d) (power-state ?d on))
                           :add-list '((connection ?d computer))))
           (let ((plan (gp-use-procedure :name 'connect-iface)))
             (is-true (plan-success plan))
             (is (= 2 (plan-length plan)))
             (is (eq 'connect-iface (getf (plan-meta plan) :from-procedure)))
             (is (fact-p '(connection interface-01 computer)
                         (plan-final-state plan)))
             (is (eq plan (gp-last-plan))))
           (is (search "Reused procedure" (gp-explain :plan nil))))
      (ignore-errors (delete-file path)))))

(test archive-autoload-after-clear-image-memory
  (let* ((path (merge-pathnames
                (format nil "automa-gp-archive-auto-~A.agp" (get-universal-time))
                (uiop:temporary-directory)))
         (*procedure-archive-path* path)
         (*procedure-archive-autosave* t)
         (*procedure-archive-autoload* t))
    (unwind-protect
         (progn
           (gp-clear-memory)
           (%archive-studio)
           (gp-remember-procedure :name 'auto-connect)
           (setf *procedural-memory* nil
                 automa-gp::*procedure-archive-loaded* nil)
           (is (eq 'auto-connect
                   (procedure-name (gp-find-procedure 'auto-connect)))))
      (ignore-errors (delete-file path)))))

(test archive-plan-reuses-applicable-procedure
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (let ((plan (gp-plan :goals '((connection interface-01 computer)))))
    (is (eq 'once (getf (plan-meta plan) :from-procedure)))
    (is (= 2 (plan-length plan)))
    (is (fact-p '(connection interface-01 computer) (plan-final-state plan)))
    (is (fact-p '(power-state interface-01 off) (gp-facts))))
  (multiple-value-bind (text tr) (gp-explain :plan nil)
    (is (deliberative-trace-p tr))
    (is (search "Reused procedure" text))
    (is (search "POWER-ON" text))))

(test archive-use-ends-plan-failed-listening
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (let ((failed (gp-plan :goals '((ready interface-01)) :archive nil)))
    (is (not (plan-success failed)))
    (is (observation-active-p))
    (is (eq :plan-failed (getf (gp-observation) :reason))))
  (let ((plan (gp-use-procedure :name 'once)))
    (is (plan-success plan))
    (is (eq 'once (getf (plan-meta plan) :from-procedure)))
    (is (not (observation-active-p)))
    (is (null *observed-before*))
    (signals error (gp-induce-rule 'stale))
    (signals error (gp-learn-action 'stale)))
  (gp-listen :reason :manual)
  (is (observation-active-p))
  (gp-use-procedure :name 'once)
  (is (observation-active-p))
  (is (eq :manual (getf (gp-observation) :reason))))

(test archive-plan-reuses-procedure-whose-goals-include-the-request
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'draw-noted
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty) (note ?d poured))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)
                    (note interface-01 poured))
           :archive nil)
  (gp-remember-procedure :name 'wide-fill)
  (let ((plan (gp-plan :goals '((charge-state interface-01 empty)))))
    (is (eq 'wide-fill (getf (plan-meta plan) :from-procedure)))
    (is (eq 'draw-noted (getf (first (plan-steps plan)) :operator)))
    (is (fact-p '(note interface-01 poured) (plan-final-state plan)))
    (is (fact-p '(charge-state interface-01 empty) (plan-final-state plan)))
    (is (not (fact-p '(note interface-01 poured) (gp-facts)))))
  (let ((text (gp-explain :plan nil)))
    (is (search "WIDE-FILL" text)))
  (let ((sim (gp-simulate)))
    (is-true (execution-success sim))
    (is (not (fact-p '(note interface-01 poured) (gp-facts))))
    (is (fact-p '(reservoir interface-01 full) (gp-facts))))
  (let ((run (gp-run)))
    (is-true (execution-success run))
    (is (fact-p '(note interface-01 poured) (gp-facts)))
    (is (fact-p '(charge-state interface-01 empty) (gp-facts)))
    (is (not (fact-p '(reservoir interface-01 full) (gp-facts))))))

(test archive-plan-prefers-exact-goals-over-a-covering-procedure
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'draw
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)) :archive nil)
  (gp-remember-procedure :name 'exact-fill)
  (gp-add-operator
   (make-operator :name 'draw-noted
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty) (note ?d poured))
                  :delete-list '((reservoir ?d full))))
  (gp-plan :goals '((charge-state interface-01 empty)
                    (note interface-01 poured))
           :archive nil)
  (gp-remember-procedure :name 'wide-fill)
  (gp-score-procedure 'wide-fill :success t)
  (gp-score-procedure 'wide-fill :success t)
  (is (> (procedure-score (gp-find-procedure 'wide-fill))
         (procedure-score (gp-find-procedure 'exact-fill))))
  (let ((plan (gp-plan :goals '((charge-state interface-01 empty)))))
    (is (eq 'exact-fill (getf (plan-meta plan) :from-procedure)))
    (is (eq 'draw (getf (first (plan-steps plan)) :operator)))
    (is (not (fact-p '(note interface-01 poured) (plan-final-state plan))))))

(test archive-plan-skips-a-covering-procedure-that-does-not-apply
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'draw-noted
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty) (note ?d poured))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)
                    (note interface-01 poured))
           :archive nil)
  (gp-remember-procedure :name 'wide-fill)
  (gp-remove-operator 'draw-noted)
  (gp-remove-fact '(reservoir interface-01 full))
  (gp-add-fact '(bucket interface-01 full))
  (gp-add-operator
   (make-operator :name 'scoop
                  :preconditions '((device ?d) (bucket ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((bucket ?d full))))
  (let ((plan (gp-plan :goals '((charge-state interface-01 empty)))))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (eq 'scoop (getf (first (plan-steps plan)) :operator)))
    (is (not (fact-p '(note interface-01 poured) (plan-final-state plan))))))

(test archive-plan-combines-procedures-that-each-cover-part
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)) :archive nil)
  (gp-remember-procedure :name 'fill-empty)
  (gp-remove-operator 'pour)
  (gp-add-operator
   (make-operator :name 'attach
                  :preconditions '((device ?d) (socket ?d free))
                  :add-list '((cable ?d connected))
                  :delete-list '((socket ?d free))))
  (gp-add-fact '(socket interface-01 free))
  (gp-plan :goals '((cable interface-01 connected)) :archive nil)
  (gp-remember-procedure :name 'plug-cable)
  (gp-remove-operator 'attach)
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty)
                                 (cable interface-01 connected))))
         (steps (plan-steps plan)))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (equal '(fill-empty plug-cable)
               (getf (plan-meta plan) :from-procedures)))
    (is (eq 'pour (getf (first steps) :operator)))
    (is (eq t (getf (first steps) :stored-apply)))
    (is (eq 'attach (getf (second steps) :operator)))
    (is (eq t (getf (second steps) :stored-apply)))
    (is (fact-p '(charge-state interface-01 empty) (plan-final-state plan)))
    (is (fact-p '(cable interface-01 connected) (plan-final-state plan)))
    (is (not (fact-p '(charge-state interface-01 empty) (gp-facts)))))
  (let ((text (gp-explain :plan nil)))
    (is (search "FILL-EMPTY" text))
    (is (search "PLUG-CABLE" text)))
  (let ((fill-before (procedure-success-count (gp-find-procedure 'fill-empty)))
        (plug-before (procedure-success-count (gp-find-procedure 'plug-cable))))
    (let ((sim (gp-simulate)))
      (is-true (execution-success sim))
      (is (fact-p '(reservoir interface-01 full) (gp-facts)))
      (is (fact-p '(socket interface-01 free) (gp-facts)))
      (is (= fill-before (procedure-success-count (gp-find-procedure 'fill-empty)))))
    (let ((run (gp-run)))
      (is-true (execution-success run))
      (is (fact-p '(charge-state interface-01 empty) (gp-facts)))
      (is (fact-p '(cable interface-01 connected) (gp-facts)))
      (is (not (fact-p '(reservoir interface-01 full) (gp-facts))))
      (is (not (fact-p '(socket interface-01 free) (gp-facts))))
      (is (= (1+ fill-before)
             (procedure-success-count (gp-find-procedure 'fill-empty))))
      (is (= (1+ plug-before)
             (procedure-success-count (gp-find-procedure 'plug-cable)))))))

(test archive-plan-prefers-one-covering-procedure-over-parts
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)) :archive nil)
  (gp-remember-procedure :name 'fill-empty)
  (gp-score-procedure 'fill-empty :success t)
  (gp-remove-operator 'pour)
  (gp-add-operator
   (make-operator :name 'attach
                  :preconditions '((device ?d) (socket ?d free))
                  :add-list '((cable ?d connected))
                  :delete-list '((socket ?d free))))
  (gp-add-fact '(socket interface-01 free))
  (gp-plan :goals '((cable interface-01 connected)) :archive nil)
  (gp-remember-procedure :name 'plug-cable)
  (gp-score-procedure 'plug-cable :success t)
  (gp-remove-operator 'attach)
  (gp-add-operator
   (make-operator :name 'prep-both
                  :preconditions '((device ?d) (reservoir ?d full) (socket ?d free))
                  :add-list '((charge-state ?d empty) (cable ?d connected))
                  :delete-list '((reservoir ?d full) (socket ?d free))))
  (gp-plan :goals '((charge-state interface-01 empty)
                    (cable interface-01 connected))
           :archive nil)
  (gp-remember-procedure :name 'prep-all)
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty)
                                 (cable interface-01 connected))))
         (text (gp-explain :plan nil)))
    (is (eq 'prep-all (getf (plan-meta plan) :from-procedure)))
    (is (eq 'prep-both (getf (first (plan-steps plan)) :operator)))
    (is (search "PREP-ALL" text))
    (is (not (search "FILL-EMPTY" text)))))

(test archive-plan-uses-search-for-the-part-left-over
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)) :archive nil)
  (gp-remember-procedure :name 'fill-empty)
  (gp-remove-operator 'pour)
  (gp-add-operator
   (make-operator :name 'attach
                  :preconditions '((device ?d) (socket ?d free))
                  :add-list '((cable ?d connected))
                  :delete-list '((socket ?d free))))
  (gp-add-fact '(socket interface-01 free))
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty)
                                 (cable interface-01 connected))))
         (steps (plan-steps plan)))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (eq 'pour (getf (first steps) :operator)))
    (is (eq t (getf (first steps) :stored-apply)))
    (is (eq 'attach (getf (second steps) :operator)))
    (is (null (getf (second steps) :stored-apply)))
    (is (fact-p '(cable interface-01 connected) (plan-final-state plan))))
  (is (search "FILL-EMPTY" (gp-explain :plan nil))))

(test archive-plan-combines-a-procedure-that-also-achieves-something-else
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'pour-noted
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty) (note ?d poured))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)
                    (note interface-01 poured))
           :archive nil)
  (gp-remember-procedure :name 'fill-noted)
  (gp-remove-operator 'pour-noted)
  (gp-add-operator
   (make-operator :name 'attach
                  :preconditions '((device ?d) (socket ?d free))
                  :add-list '((cable ?d connected))
                  :delete-list '((socket ?d free))))
  (gp-add-fact '(socket interface-01 free))
  (gp-plan :goals '((cable interface-01 connected)) :archive nil)
  (gp-remember-procedure :name 'plug-cable)
  (gp-remove-operator 'attach)
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty)
                                 (cable interface-01 connected))))
         (steps (plan-steps plan)))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (eq 'attach (getf (first steps) :operator)))
    (is (eq t (getf (first steps) :stored-apply)))
    (is (eq 'pour-noted (getf (second steps) :operator)))
    (is (eq t (getf (second steps) :stored-apply)))
    (is (fact-p '(note interface-01 poured) (plan-final-state plan)))
    (is (fact-p '(cable interface-01 connected) (plan-final-state plan)))
    (is (not (fact-p '(note interface-01 poured) (gp-facts)))))
  (let ((text (gp-explain :plan nil)))
    (is (search "FILL-NOTED" text))
    (is (search "PLUG-CABLE" text)))
  (let ((sim (gp-simulate)))
    (is-true (execution-success sim))
    (is (not (fact-p '(note interface-01 poured) (gp-facts))))
    (is (fact-p '(reservoir interface-01 full) (gp-facts))))
  (let ((run (gp-run)))
    (is-true (execution-success run))
    (is (fact-p '(note interface-01 poured) (gp-facts)))
    (is (fact-p '(charge-state interface-01 empty) (gp-facts)))
    (is (fact-p '(cable interface-01 connected) (gp-facts)))
    (is (not (fact-p '(reservoir interface-01 full) (gp-facts))))
    (is (not (fact-p '(socket interface-01 free) (gp-facts))))))

(test archive-plan-prefers-a-part-without-extra-goals
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((charge-state interface-01 empty)) :archive nil)
  (gp-remember-procedure :name 'fill-empty)
  (gp-remove-operator 'pour)
  (gp-add-operator
   (make-operator :name 'pour-noted
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty) (note ?d poured))
                  :delete-list '((reservoir ?d full))))
  (gp-plan :goals '((charge-state interface-01 empty)
                    (note interface-01 poured))
           :archive nil)
  (gp-remember-procedure :name 'fill-noted)
  (gp-score-procedure 'fill-noted :success t)
  (gp-score-procedure 'fill-noted :success t)
  (gp-remove-operator 'pour-noted)
  (is (> (procedure-score (gp-find-procedure 'fill-noted))
         (procedure-score (gp-find-procedure 'fill-empty))))
  (gp-add-operator
   (make-operator :name 'attach
                  :preconditions '((device ?d) (socket ?d free))
                  :add-list '((cable ?d connected))
                  :delete-list '((socket ?d free))))
  (gp-add-fact '(socket interface-01 free))
  (gp-plan :goals '((cable interface-01 connected)) :archive nil)
  (gp-remember-procedure :name 'plug-cable)
  (gp-remove-operator 'attach)
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty)
                                 (cable interface-01 connected))))
         (text (gp-explain :plan nil)))
    (is (eq 'pour (getf (first (plan-steps plan)) :operator)))
    (is (not (fact-p '(note interface-01 poured) (plan-final-state plan))))
    (is (search "FILL-EMPTY" text))
    (is (not (search "FILL-NOTED" text)))))

(test archive-plan-keeps-useful-steps-when-extra-goals-are-blocked
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'stamp
                  :preconditions '((device ?d) (ink ?d ready))
                  :add-list '((note ?d poured))))
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(ink interface-01 ready))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((note interface-01 poured)
                    (charge-state interface-01 empty))
           :archive nil)
  (gp-remember-procedure :name 'fill-noted)
  (is (= 2 (length (procedure-steps (gp-find-procedure 'fill-noted)))))
  (gp-remove-operator 'stamp)
  (gp-remove-operator 'pour)
  (gp-remove-fact '(ink interface-01 ready))
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty))))
         (operators (mapcar (lambda (step) (getf step :operator))
                            (plan-steps plan))))
    (is (eq 'fill-noted (getf (plan-meta plan) :from-procedure)))
    (is (eq 'pour (getf (first (plan-steps plan)) :operator)))
    (is (not (member 'stamp operators)))
    (is (not (fact-p '(note interface-01 poured) (plan-final-state plan))))
    (is (fact-p '(charge-state interface-01 empty) (plan-final-state plan))))
  (let ((text (gp-explain :plan nil)))
    (is (search "Left aside" text))
    (is (search "STAMP" text))
    (is (search "FILL-NOTED" text)))
  (let ((sim (gp-simulate)))
    (is-true (execution-success sim))
    (is (not (fact-p '(note interface-01 poured) (gp-facts))))
    (is (fact-p '(reservoir interface-01 full) (gp-facts))))
  (let ((run (gp-run)))
    (is-true (execution-success run))
    (is (fact-p '(charge-state interface-01 empty) (gp-facts)))
    (is (not (fact-p '(note interface-01 poured) (gp-facts))) )
    (is (not (fact-p '(reservoir interface-01 full) (gp-facts))))))

(test archive-plan-keeps-a-partial-step-when-its-extra-goal-is-blocked
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'stamp
                  :preconditions '((device ?d) (ink ?d ready))
                  :add-list '((note ?d poured))))
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(ink interface-01 ready))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((note interface-01 poured)
                    (charge-state interface-01 empty))
           :archive nil)
  (gp-remember-procedure :name 'fill-noted)
  (gp-remove-operator 'stamp)
  (gp-remove-operator 'pour)
  (gp-remove-fact '(ink interface-01 ready))
  (gp-add-operator
   (make-operator :name 'attach
                  :preconditions '((device ?d) (socket ?d free))
                  :add-list '((cable ?d connected))
                  :delete-list '((socket ?d free))))
  (gp-add-fact '(socket interface-01 free))
  (gp-plan :goals '((cable interface-01 connected)) :archive nil)
  (gp-remember-procedure :name 'plug-cable)
  (gp-remove-operator 'attach)
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty)
                                 (cable interface-01 connected))))
         (steps (plan-steps plan))
         (operators (mapcar (lambda (step) (getf step :operator)) steps)))
    (is (eq 'attach (getf (first steps) :operator)))
    (is (eq 'pour (getf (second steps) :operator)))
    (is (not (member 'stamp operators)))
    (is (not (fact-p '(note interface-01 poured) (plan-final-state plan)))))
  (let ((text (gp-explain :plan nil)))
    (is (search "Left aside" text))
    (is (search "STAMP" text))
    (is (search "FILL-NOTED" text))
    (is (search "PLUG-CABLE" text))))

(test archive-plan-skips-a-procedure-whose-useful-step-is-also-blocked
  (gp-clear-memory)
  (gp-reset)
  (gp-add-operator
   (make-operator :name 'stamp
                  :preconditions '((device ?d) (ink ?d ready))
                  :add-list '((note ?d poured))))
  (gp-add-operator
   (make-operator :name 'pour
                  :preconditions '((device ?d) (reservoir ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((reservoir ?d full))))
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(ink interface-01 ready))
  (gp-add-fact '(reservoir interface-01 full))
  (gp-plan :goals '((note interface-01 poured)
                    (charge-state interface-01 empty))
           :archive nil)
  (gp-remember-procedure :name 'fill-noted)
  (gp-remove-operator 'stamp)
  (gp-remove-operator 'pour)
  (gp-remove-fact '(ink interface-01 ready))
  (gp-remove-fact '(reservoir interface-01 full))
  (gp-add-fact '(bucket interface-01 full))
  (gp-add-operator
   (make-operator :name 'scoop
                  :preconditions '((device ?d) (bucket ?d full))
                  :add-list '((charge-state ?d empty))
                  :delete-list '((bucket ?d full))))
  (let* ((plan (gp-plan :goals '((charge-state interface-01 empty))))
         (text (gp-explain :plan nil)))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (eq 'scoop (getf (first (plan-steps plan)) :operator)))
    (is (not (fact-p '(note interface-01 poured) (plan-final-state plan))))
    (is (not (search "FILL-NOTED" text)))))

(test archive-plan-skips-steps-already-achieved
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'from-off)
  (gp-remove-fact '(power-state interface-01 off))
  (gp-add-fact '(power-state interface-01 on))
  (let ((plan (gp-plan :goals '((connection interface-01 computer)))))
    (is (eq 'from-off (getf (plan-meta plan) :from-procedure)))
    (is (= 1 (plan-length plan)))
    (is (eq 'connect (getf (first (plan-steps plan)) :operator)))
    (is (fact-p '(connection interface-01 computer) (plan-final-state plan))))
  (let ((text (gp-explain :plan nil)))
    (is (search "already satisfied" text))
    (is (search "CONNECT" text))))

(test archive-plan-falls-back-when-steps-do-not-apply
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'from-off)
  (gp-remove-fact '(power-state interface-01 off))
  (gp-add-fact '(battery interface-01 charged))
  (gp-add-operator
   (make-operator :name 'boot
                  :preconditions '((device ?d) (battery ?d charged))
                  :add-list '((power-state ?d on))))
  (let ((plan (gp-plan :goals '((connection interface-01 computer)))))
    (is-true (plan-success plan))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (member 'boot (plan-operators-used plan)))))

(test archive-plan-can-skip-archive
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (let ((plan (gp-plan :goals '((connection interface-01 computer))
                       :archive nil)))
    (is-true (plan-success plan))
    (is (null (getf (plan-meta plan) :from-procedure)))
    (is (>= (plan-length plan) 2))))

(test autonomy-reuses-archive-before-search
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (gp-reset)
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(power-state interface-01 off))
  (gp-add-operator
   (make-operator :name 'power-on
                  :preconditions '((device ?d) (power-state ?d off))
                  :add-list '((power-state ?d on))
                  :delete-list '((power-state ?d off))))
  (gp-add-operator
   (make-operator :name 'connect
                  :preconditions '((device ?d) (power-state ?d on))
                  :add-list '((connection ?d computer))))
  (gp-add-goal '(connection interface-01 computer))
  (let ((summary (gp-autonomous-step
                  :policy (make-autonomy-policy :authority :simulate
                                                :prefer-archive t))))
    (is (eq :done (getf summary :status)))
    (is (eq 'once (getf (getf summary :plan) :from-procedure)))
    (is (eq 'once (getf (plan-meta (gp-last-plan)) :from-procedure)))
    (is (fact-p '(power-state interface-01 off) (gp-facts)))
    (is (= 1 (procedure-success-count (gp-find-procedure 'once))))
    (is (= 0 (procedure-failure-count (gp-find-procedure 'once))))))

(test archive-live-run-raises-score-simulation-does-not
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (gp-plan :goals '((connection interface-01 computer)))
  (gp-simulate)
  (is (= 1 (procedure-success-count (gp-find-procedure 'once))))
  (is (= 0 (procedure-failure-count (gp-find-procedure 'once))))
  (gp-reset)
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(power-state interface-01 off))
  (gp-add-operator
   (make-operator :name 'power-on
                  :preconditions '((device ?d) (power-state ?d off))
                  :add-list '((power-state ?d on))
                  :delete-list '((power-state ?d off))))
  (gp-add-operator
   (make-operator :name 'connect
                  :preconditions '((device ?d) (power-state ?d on))
                  :add-list '((connection ?d computer))))
  (let ((run (gp-run :plan (gp-plan :goals '((connection interface-01 computer))))))
    (is-true (execution-success run))
    (is (= 2 (procedure-success-count (gp-find-procedure 'once))))
    (is (= 0 (procedure-failure-count (gp-find-procedure 'once)))))
  (gp-reset)
  (gp-add-fact '(device interface-01))
  (gp-add-fact '(power-state interface-01 off))
  (gp-add-operator
   (make-operator :name 'power-on
                  :preconditions '((device ?d) (power-state ?d off))
                  :add-list '((power-state ?d on))
                  :delete-list '((power-state ?d off))))
  (gp-add-operator
   (make-operator :name 'connect
                  :preconditions '((device ?d) (power-state ?d on))
                  :add-list '((connection ?d computer))))
  (gp-plan :goals '((connection interface-01 computer)) :archive nil)
  (gp-run)
  (is (= 2 (procedure-success-count (gp-find-procedure 'once)))))

(test archive-live-failure-lowers-score
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (gp-remove-fact '(device interface-01))
  (signals error (gp-use-procedure :name 'once))
  (gp-use-procedure :name 'once :unchecked t)
  (let ((run (with-failure-strategy (:abort)
               (gp-run))))
    (is (not (execution-success run))))
  (is (= 1 (procedure-success-count (gp-find-procedure 'once))))
  (is (= 1 (procedure-failure-count (gp-find-procedure 'once))))
  (is (< (procedure-score (gp-find-procedure 'once))
         (procedure-score
          (make-procedure :name 'baseline :success-count 1 :failure-count 0)))))

(test autonomy-execute-scores-reused-procedure
  (gp-clear-memory)
  (%archive-studio)
  (gp-remember-procedure :name 'once)
  (gp-add-goal '(connection interface-01 computer))
  (let ((summary (gp-autonomous-step
                  :policy (make-autonomy-policy :authority :execute
                                                :prefer-archive t
                                                :remember-procedure t))))
    (is (eq :done (getf summary :status)))
    (is (eq 'once (getf (getf summary :plan) :from-procedure)))
    (let ((proc (gp-find-procedure 'once)))
      (is (= 2 (procedure-success-count proc)))
      (is (= 0 (procedure-failure-count proc))))
    (is (= 1 (count-if (lambda (p)
                         (eq 'once (procedure-name p)))
                       (gp-procedures))))))
